name: vdi_bank
description: Vdi bank.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.1.1 # quan ly state he thong
  get_it: ^4.0.4
  get_storage: ^2.0.2 #store
  permission_handler: ^6.1.1 # xin quyen
  connectivity: ^3.0.3 #check connect
  transparent_image: ^2.0.0 #loading image
  flutter_spinkit: ^4.1.2 #loadding
  shimmer: ^1.1.2 # placehover list loading
  line_icons: ^0.2.0 #icon ??p
  pin_code_fields: ^7.0.0 #otp code ui
  qrscan: ^0.3.1 #qr code scannser

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/bg.jpg
    - assets/images/bgmenu.jpg
    - assets/images/brvav.png
    - assets/images/splash.gif
    - assets/images/logo.png
    - assets/images/ic_user.png
    - assets/images/ic_lock.png
    - assets/images/background_login.jpg
    - assets/images/avata.jpg
    - assets/images/cover_dashboard.png
    - assets/images/postage_texture.png
    - assets/images/back.png
    - assets/images/customer.png
    - assets/images/dacbiet.png
    - assets/images/icon_scan.png
    - assets/images/icon_shipping.png
    - assets/images/icon_tiepnhan.png
    - assets/images/icon_more.png
    - assets/images/icon_notification.png
    - assets/images/icon_history.png
    - assets/images/maps.png
    - assets/images/background_dark.jpg
    - assets/images/accept_icon.png
    - assets/images/package_unknow.png
    - assets/images/package_know.png
    - assets/images/icon_en.png
    - assets/images/icon_vi.png
    - assets/images/group_postage.png
    - assets/images/icon_map.png
    - assets/images/image_loading.gif
    - assets/images/vpbank_smartotp_icon.png
    - assets/images/icon_bee.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Light.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
